apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.portico.gatewayClassName }}
  labels:
    {{- include "portico.labels" . | nindent 4 }}
spec:
  controllerName: {{ .Values.portico.gatewayControllerName }}
