version: "3"

tasks:
  create-kind-cluster:
    cmds:
      - kind create cluster --config kind.yaml

  apply-gateway-api-standard:
    cmds:
      - kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml
